# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.


# Site Settings
locale                   : "en-US"
title                    : Tyson Russell
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : Tyson Russell
description              : Tyson Russell - Projects and CV 
baseurl                  : "/fa25-portfolio-ter5521/" # Set this to your repo name 

# Theme and Style
theme: jekyll-theme-minimal
color_scheme: light # light/default, dark, or aqua

sass:
  style: compressed

# Markdown and Math
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

# Outputting
permalink: /:categories/:title/

collections:
  pages:
    output: true
  projects:
    output: true
    permalink: /:collection/:path/

# Plugins (previously gems:)
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag

